language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
sudo: false
before_script:
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo build
  - cargo test
  - cargo bench
